FROM caddy:latest
COPY . /var/www/html/public
RUN wget https://github.com/highlightjs/cdn-release/archive/refs/tags/11.9.0.zip && unzip 11.9.0.zip && mv cdn-release-11.9.0 highlightjs && rm 11.9.0.zip
