FROM caddy:latest
COPY ./src /var/www/html/public
COPY composer_install.sh composer.json /var/www/html/public/
RUN wget https://github.com/highlightjs/cdn-release/archive/refs/tags/11.9.0.zip && unzip 11.9.0.zip && mv cdn-release-11.9.0/build /var/www/html/public/highlightjs && rm 11.9.0.zip
